### ISSUE TITLE
Check anonymous user

### ISSUE THREAD

**Issue by bogdandm** [rsinger86/drf-access-policy#4]
https://github.com/rsinger86/drf-access-policy/blob/master/rest_access_policy/access_policy.py#L79

This line will raise an error if user is not authorized. 

It can be fixed by lazy function with is_authorized check (you do implicit `is_authorized` check only if user should be in some group) or could move `user_roles = self.get_user_group_values(user)` into `for` loop under condition and cache it value.

**Comment by rsinger86** [comment]
Good catch. I'm thinking that `get_user_group_values` should return empty list if user is anonymous.

**Comment by rsinger86** [comment]
Hmm, since DRF will set request.user to an instance of `django.contrib.auth.models.AnonymousUser` if no authentication methods succeeds, I'm not sure we even need to check this. 

Looking at the Django's class def of AnonymousUser, it looks to have the required props/methods to make it compatible with this project:
https://github.com/django/django/blob/master/django/contrib/auth/models.py#L364

Let me know if I'm missing something,

**Comment by bogdandm** [comment]
Hmm, you are right. My bad, don't look at `AnonymousUser` for a while. Already forgot that it implement User interface.

Anyway, in many projects there're `IsAuthorizedOrReadOnly` politic. So how do I can setup it with your project? I think we still need something like `"principal": "anonymous"`

**Comment by rsinger86** [comment]
I've been thinking about providing "built-in" conditions for common cases like this, where it'd be a pain to write the same custom method over and over (you may have noticed I linked to [this](https://github.com/rsinger86/drf-access-policy/issues/1) in another issue)

What do you think about this approach? Having certain common conditions be handled by passing in a dictionary instead of a string:

```json
    {
        "action": ["*"],
        "principal": "*",
        "effect": "allow",
        "condition": {"is_authenticated_or_read_only": true}
    }
```

This statement would grant access if either of following were true: user  is authenticated or  the action is "read_only" (request method is one of HEAD, OPTIONS, GET). Do you think this would handle the use case you mentioned?

**Comment by bogdandm** [comment]
In your example I don't like that fact that `"condition"` contains some `"action"` logic. You already provide built-in principal related to user data, so I think `condition` should stay as custom filter (function of class reference as I mentioned in PR) while `principal` contains all basic logic like: 
* `authorized` (equivalent of `*`)
* `anonymous`
* `group:<group_name>`
* `id:<user_id>`
* `name:<username>`
* `admin`

Perhaps I don't understand some concepts. I don't use and even hear about _AWS' IAM_ so maybe I miss something.

**Comment by rsinger86** [comment]
Yeah, I think you're right - best to keep actions separate. What do you think of a placeholder/variable syntax to reference types of actions or principals? 

Principals:
`*`: would continue to match any user, authenticated or not
`<authenticated>`: would match any authenticated user
`<anonymous>`: would match any non-authenticated user

Actions:
`<read_only>` or alternatively, `<safe_methods>`: would match an action of a request that was HEAD, OPTIONS, GET

Then to set up an `IsAuthorizedOrReadOnly` scenario you could do:
```json
[
    {
        "principal": "<authenticated>",
        "action": "*",
        "effect": "allow"
    },
    {
        "principal": "<anonymous>",
        "action": "<read_only>",
        "effect": "allow"
    }
]
```

**Comment by bogdandm** [comment]
`"action": "<safe_methods>"` - :+1: 

But why do you want `<>` for `principal`? For me it is just unnessesary "noise". Just `"principal": "authenticated"` would be fine.

P.S. One thing that bothers me is perfomance and optimization. There is a lot of `resolve` methods and some of them could be cached I think.

**Comment by rsinger86** [comment]
Yeah, point taken on unneeded `<>`. I'm inclined to agree.

Agreed on performance too. I think the biggest culprit is probably that `view.get_object()` isn't cached. The non-I/O stuff could probably be optimized some too, though I'd rather focus on getting the baseline features done for now.

**Comment by rsinger86** [comment]
Thanks again for your feedback. In the latest release, `authenticated` and `anonymous` have been added for the principal, and `<safe_methods` for the action.
