### ISSUE TITLE
Why "principal: authenticated" is "not anonymous" instead of "is authenticated"?

### ISSUE THREAD

**Issue by danyi1212** [rsinger86/drf-access-policy#80]
Hey @rsinger86,

After reading the code a bit, I stumbled across the code for matching principal on statements.
I found out the code at [access_policy.py line 142](https://github.com/rsinger86/drf-access-policy/blob/f627c50980f37bba1d52a6697d80d1c5daf7fbe9/rest_access_policy/access_policy.py#L142) that the ["authenticated" value for principal](https://rsinger86.github.io/drf-access-policy/statement_elements.html#principal) checks that the user is not anonymous instead of actually whether it is authenticated or not.

Out of curiosity, why is that implemented like so and not using [built-in "is_authenticated"](https://docs.djangoproject.com/en/4.0/ref/contrib/auth/#django.contrib.auth.models.User.is_authenticated)?
Is there a difference?

Thank you!

**Comment by rsinger86** [comment]
Good question :) 

I had forgotten why, but going back over the commit history there was a point where we decided to support an edge case where the request.user is `None` due to the project not using Django's authentication middleware. 

To make it work in this case, I added a custom AnonymousUser object here:
https://github.com/rsinger86/drf-access-policy/blob/master/rest_access_policy/access_policy.py#L14

This could be updated to have the same interface as Django's AnonymousUser.
